<?php
/**
 * @file
 * Code for the Shoov Build feature.
 */

include_once 'shoov_ui_build.features.inc';

/**
 * Implements hook_node_insert().
 */
function shoov_ui_build_node_insert($node) {
  if ($node->type != 'ui_build') {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);

  $repo_id = $wrapper->og_repo->value(array('identifier' => TRUE));


  $account = user_load($node->uid);
  $handler = restful_get_restful_handler('builds');
  $handler->setAccount($account);
  $result = $handler->get($node->nid);

  shoov_pusher_trigger_event($repo_id, 'new_ui_build', $result[0]);
}

/**
 * Implements hook_node_update().
 */
function shoov_ui_build_node_update($node) {
  if ($node->type != 'ui_build') {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);


  $repo_id = $wrapper->og_repo->value(array('identifier' => TRUE));
  $status = $wrapper->field_pull_request_status->value();
  $data = array('status' => $status);
  shoov_pusher_trigger_event($repo_id, 'ui_build_pull_request', $data);


  if ($status != 'requested') {
    return;
  }

  shoov_ui_build_create_pr($node);
}

/**
 * Call the Pull request server with the right arguments.
 *
 * @param $node
 *   The Build node object.
 *
 * @return object|void
 *   The response object.
 *
 * @throws \Exception
 */
function shoov_ui_build_create_pr($node) {
  $wrapper = entity_metadata_wrapper('node', $node);

  if (!$screenshot_ids = $wrapper->field_pr_screenshot_ids->value()) {
    // @todo: Add validation to see this doesn't happen if there was a request.
    return;
  }

  // Send a request.
  $url = variable_get('shoov_ui_build_pr_server', 'http://localhost:3000');
  if (!$url) {
    throw new Exception('Shoov UI build PR server is not setup.');
  }

  // {build Id}/{screenshot IDs}/{new branch}/{access token}
  $url = array(
    $url,
    'create_pr',
    $node->nid,
    $screenshot_ids,
    $wrapper->field_pr_branch_name->value(),
    // User's RESTful token.
    shoov_restful_get_user_token(),
  );

  $url = implode('/', $url);

  return drupal_http_request($url);
}
