<?php
/**
 * @file
 * Code for the Shoov Build feature.
 */

include_once 'shoov_ui_build.features.inc';

/**
 * Implements hook_node_update().
 *
 * @param $node
 */
function shoov_ui_build_node_update($node) {
  if ($node->type != 'build') {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  if ($wrapper->field_pull_request_status->value() != 'requested') {
    return;
  }

  shoov_ui_build_create_pr($node);
}

/**
 * Call the Pull request server with the right arguments.
 *
 * @param $node
 *   The Build node object.
 *
 * @return object|void
 *   The response object.
 *
 * @throws \Exception
 */
function shoov_ui_build_create_pr($node) {
  $wrapper = entity_metadata_wrapper('node', $node);

  if (!$screenshot_ids = $wrapper->field_pr_screenshot_ids->value()) {
    // @todo: Add validation to see this doesn't happen if there was a request.
    return;
  }

  // Send a request.
  $url = variable_get('shoov_ui_build_pr_server', 'http://localhost:3000');
  if (!$url) {
    throw new Exception('Shoov UI build PR server is not setup.');
  }

  // {build Id}/{screenshot IDs}/{new branch}/{access token}
  $url = array(
    $url,
    'create_pr',
    $node->nid,
    $screenshot_ids,
    $wrapper->field_pr_branch_name->value(),
    // User's RESTful token.
    shoov_restful_get_user_token(),
  );

  $url = implode('/', $url);

  return drupal_http_request($url);
}
