<?php
/**
 * @file
 * Code for the Shoov CI Incident feature.
 */

include_once 'shoov_ci_incident.features.inc';


/**
 * Return an incident of a CI build.
 *
 * @param stdClass $node
 *   The CI build node object.
 *
 * @return stdClass | null
 *   The CI incident node object if found, or NULL.
 */
function shoov_ci_incident_get_latest_error_incident($node) {
  $account = user_load($node->uid);

  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'ci_incident')
    ->fieldCondition('field_ci_build', 'target_id', $node->nid)
    ->fieldCondition('field_ci_build_error', 'value', TRUE)
    ->propertyCondition('status', NODE_PUBLISHED)
    ->range(0, 1)
    // Set the user account as the node author, to prevent node access from
    // hiding the result.
    ->addMetaData('account', $account)
    ->execute();

  if (empty($result['node'])) {
    return;
  }

  $id = key($result['node']);
  return node_load($id);
}

/**
 * Create an error incident node.
 *
 * @param \Message $message
 *   The "ci_build" message object.
 *
 * @return stdClass
 *   The newly saved CI incident node object.
 */
function shoov_ci_incident_create_error_incident(Message $message) {
  $message_wrapper = entity_metadata_wrapper('message', $message);
  $ci_build_id = $message_wrapper->field_ci_build->getIdentifier();

  $params = array(
    '@count' => shoov_ci_incident_get_incidents_count($ci_build_id) + 1,
  );

  $values = array(
    'type' => 'ci_incident',
    'title' => format_string('Incident @count', $params),
    'uid' => $message->uid,
  );


  $node = entity_create('node', $values);
  $wrapper = entity_metadata_wrapper('node', $node);

  $wrapper->og_repo->set($message_wrapper->field_ci_build->og_repo->getIdentifier());
  $wrapper->field_ci_build->set($ci_build_id);
  $wrapper->field_failing_build->set($message);
  $wrapper->field_ci_build_error->set(TRUE);
  $wrapper->save();

  return $node;
}

/**
 * Get the number of existing incidents per CI build.
 *
 * @param int $nid
 *   The CI-build node ID.
 *
 * @return int
 *   The count of CI incidents.
 */
function shoov_ci_incident_get_incidents_count($nid) {
  $query = new EntityFieldQuery();
  $count = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'ci_incident')
    ->fieldCondition('field_ci_build', 'target_id', $nid)
    ->propertyCondition('status', NODE_PUBLISHED)
    ->count()
    ->execute();

  return $count;
}