<?php
/**
 * @file
 * Code for the Shoov Repository feature.
 */

include_once 'shoov_repository.features.inc';

/**
 * Implements hook_node_presave().
 *
 * Get the GitHub repo ID for a local repository.
 */
function shoov_repository_node_presave($node) {
  if ($node->type != 'repository') {
    // Not a repository node.
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  if ($wrapper->field_github_id->value()) {
    // GitHub Id already populated.
    return;
  }

  list($owner, $repo) = explode('/', $node->title);

  $data = shoov_github_get_data_from_http_result("repo/$owner/$repo");

  // @todo: Throw exception on error?
  if (!empty($data['id'])) {
    $wrapper->field_github_id->set($data['id']);
  }
}
