<?php
/**
 * @file
 * Code for the Shoov Repository feature.
 */

include_once 'shoov_repository.features.inc';

/**
 * Implements hook_node_presave().
 *
 * Get the GitHub repo ID for a local repository.
 */
function shoov_repository_node_presave($node) {
  if ($node->type != 'repository') {
    // Not a repository node.
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  if ($wrapper->field_github_id->value()) {
    // GitHub Id already populated.
    return;
  }

  list($owner, $repo) = explode('/', $node->title);

  $user_wrapper = entity_metadata_wrapper('user', $node->uid);
  $access_token = $user_wrapper->field_github_access_token->value();

  $options = array(
    'headers' => array(
      'Authorization' => 'token ' . $access_token,
    ),
  );

  $data = shoov_github_http_request("repos/$owner/$repo", $options);

  // @todo: Throw exception on error?
  if (!empty($data['id'])) {
    $wrapper->field_github_id->set($data['id']);
  }
}

/**
 * Implements hook_node_insert().
 */
function shoov_repository_node_insert($node) {
  if ($node->type != 'repository') {
    return;
  }

  $account = user_load($node->uid);
  $handler = restful_get_restful_handler('repositories');
  $handler->setAccount($account);
  $result = $handler->get($node->nid);

  $data = array($result[0]);

  shoov_pusher_trigger_user_event($node->uid, 'new_repo', $data);
}
