<?php
/**
 * @file
 * Code for the Shoov Build feature.
 */

include_once 'shoov_build.features.inc';

/**
 * Implements hook_node_update().
 *
 * @param $node
 */
function shoov_build_node_update($node) {
  if ($node->type != 'build') {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  if ($wrapper->field_pull_request_status->value() != 'request') {
    return;
  }

  if (!$screenshot_ids = $wrapper->field_pr_screenshot_ids->value()) {
    // @todo: Add validation to see this doesn't happen if there was a request.
    return;
  }

  // Send a request.
  $url = variable_get('shoov_build_pr_server');
  if (!$url) {
    throw new Exception('Shoov build PR server is not setup.');
  }

  // {build Id}/{screenshot IDs}/{new branch}/{access token}
  $url = array(
    variable_get('shoov_build_pr_server'),
    $node->nid,
    $screenshot_ids,
    $wrapper->field_pr_branch_name->value(),
    // User's RESTful token.
    shoov_restful_get_user_token()
  );

  $url = implode('/', $url);

  drupal_http_request($url);
}
