<?php

/**
 * @file
 * Populate Boom content.
 */

/**
 * Implements hook_migrate_api().
 */
function boom_migrate_migrate_api() {
  $migrations = array(
    // Nodes.
    'BoomCompaniesMigrate',
    'BoomEventsMigrate',
    // Users.
    'BoomUsersMigrate',
  );

  $api['api'] = 2;
  foreach ($migrations as $migration) {
    $api['migrations'][$migration] = array('class_name' => $migration);
  }

  return $api;
}
