<?php

/**
 * @file
 * Populate Shoov content.
 */

/**
 * Implements hook_migrate_api().
 */
function shoov_migrate_migrate_api() {
  $migrations = array(
    // Nodes.
    'ShoovRepositoriesMigrate',
    'ShoovCiBuildsMigrate',
    'ShoovUiBuildsMigrate',
    'ShoovScreenshotsMigrate',
    'ShoovCiIncidentsMigrate',
    // Entities.
    'ShoovCiBuildMessagesMigrate',
    'ShoovCiIncidentErrorMessagesMigrate',
    'ShoovCiIncidentFixedMessagesMigrate',
    // Users.
    'ShoovUsersMigrate',
  );

  $api['api'] = 2;
  foreach ($migrations as $migration) {
    $api['migrations'][$migration] = array('class_name' => $migration);
  }

  return $api;
}
