<?php
/**
 * @file
 * Code for the RESTful integration.
 */

if (!drupal_is_cli()) {
  header('Access-Control-Allow-Origin: *');
  header('Access-Control-Allow-Credentials: true');
  header('Access-Control-Allow-Headers: Authorization, access-token');
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function shoov_restful_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Get a user token.
 *
 * @param stdClass $account
 *   (optional) The user object. If empty the current user will be used.
 * @return string
 *   The user's access token.
 */
function shoov_restful_get_user_token($account = NULL)  {
  global $user;
  $uid = $account ? $account->uid : $user->uid;
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'restful_token_auth')
    ->entityCondition('bundle', 'access_token')
    ->propertyCondition('uid', $uid)
    ->range(0, 1)
    ->execute();

  if (empty($result['restful_token_auth'])) {
    // User might not have a user token, if it was created programmatically,
    // e.g. via migrate.
    $controller = entity_get_controller('restful_token_auth');
    $access_token = $controller->generateAccessToken($uid);
    return $access_token->token;
  }

  $id = key($result['restful_token_auth']);
  $entity = entity_load_single('restful_token_auth', $id);

  return $entity->token;
}
