<?php
/**
 * @file
 * Code for the RESTful integration.
 */

if (!drupal_is_cli()) {
  header('Access-Control-Allow-Origin: *');
  header('Access-Control-Allow-Credentials: true');
  header('Access-Control-Allow-Headers: Authorization, access-token');
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function shoov_restful_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Get a user token.
 *
 * @param stdClass $account
 *   (optional) The user object. If empty the current user will be used.
 * @return string
 *   The user's access token.
 */
function shoov_restful_get_user_token($account = NULL)  {
  global $user;
  $uid = $account ? $account->uid : $user->uid;
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'restful_token_auth')
    ->entityCondition('bundle', 'access_token')
    ->propertyCondition('uid', $uid)
    ->range(0, 1)
    ->execute();

  $id = key($result['restful_token_auth']);
  $entity = entity_load_single('restful_token_auth', $id);

  return $entity->token;
}

/**
 * Implements hook_file_download_access().
 *
 * Get the user account from the RESTful authentication.
 */
function shoov_restful_file_download_access($file_item, $entity_type, $entity) {
  $auth_plugins = array_keys(restful_get_authentication_plugins());

  $auth_manager = new RestfulAuthenticationManager();

  // Register all authentication plugins.
  foreach ($auth_plugins as $auth_plugin_name) {
    $auth_handler = restful_get_authentication_handler($auth_plugin_name);
    $auth_manager->addAuthenticationProvider($auth_handler);
    $auth_manager->setIsOptional(TRUE);
  }

  $request = restful_parse_request();
  $auth_manager->getAccount($request);
}
