<?php
/**
 * @file
 * Code for the RESTful integration.
 */

if (!drupal_is_cli()) {
  header('Access-Control-Allow-Origin: *');
  header('Access-Control-Allow-Credentials: true');
  header('Access-Control-Allow-Headers: Authorization, access-token');
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function boom_restful_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return 'plugins/' . $plugin;
  }
}


/**
 * Implements hook_file_insert().
 *
 * Create a screenshot node from an uploaded file.
 */
function boom_restful_file_insert($file) {
  $values = array(
    'type' => 'screenshot',
    'uid' => $file->uid,
    'title' => $file->filename,
  );

  $node = entity_create('node', $values);
  $wrapper = entity_metadata_wrapper('node', $node);

  $wrapper->field_image->set(array('fid' => $file->fid, 'display' => TRUE));
  $wrapper->save();
}